services:
  phoenix:
    image: arizephoenix/phoenix:version-20.14.0
    restart: unless-stopped
    environment:
      - PHOENIX_ENABLE_AUTH=true
      - PHOENIX_SECRET=${PHOENIX_SECRET:?}
    volumes:
      - phoenix-data:/root/.phoenix
    networks:
      - dokploy-network

volumes:
  phoenix-data:

networks:
  dokploy-network:
    external: true
